.TH delbucket 1 "January 2017" Moray "Moray Client Tools"
.SH NAME
.PP
delbucket \- delete a bucket from Moray
.SH SYNOPSIS
.PP
\fB\fCdelbucket [COMMON_OPTIONS] BUCKET\fR
.SH DESCRIPTION
.PP
Removes the bucket called \fB\fCBUCKET\fR from Moray.  Any objects contained in the
bucket will be removed permanently.  This command fails if the bucket does not
exist.
.SH OPTIONS
.PP
See \fB\fCmoray(1)\fR for information about the \fB\fCCOMMON_OPTIONS\fR, which control
the log verbosity and how to locate the remote server.
.SH ENVIRONMENT
.PP
See \fB\fCmoray(1)\fR for information about the \fB\fCLOG_LEVEL\fR, \fB\fCMORAY_SERVICE\fR, and
\fB\fCMORAY_URL\fR environment variables.
.SH EXAMPLES
.PP
Delete a bucket called "accounts":
.PP
.RS
.nf
$ delbucket accounts
.fi
.RE
.SH SEE ALSO
.PP
\fB\fCmoray(1)\fR, \fB\fCputbucket(1)\fR
