.TH delobject 1 "January 2017" Moray "Moray Client Tools"
.SH NAME
.PP
delobject \- delete an object by primary key
.SH SYNOPSIS
.PP
\fB\fCdelobject [COMMON_OPTIONS] BUCKET KEY\fR
.SH DESCRIPTION
.PP
Removes the object in bucket \fB\fCBUCKET\fR having primary key \fB\fCKEY\fR\&.  This command
fails if the object does not exist.
.SH OPTIONS
.PP
See \fB\fCmoray(1)\fR for information about the \fB\fCCOMMON_OPTIONS\fR, which control
the log verbosity and how to locate the remote server.
.SH ENVIRONMENT
.PP
See \fB\fCmoray(1)\fR for information about the \fB\fCLOG_LEVEL\fR, \fB\fCMORAY_SERVICE\fR, and
\fB\fCMORAY_URL\fR environment variables.
.SH EXAMPLES
.PP
Remove the object in "accounts" with key "hugh":
.PP
.RS
.nf
$ delobject accounts hugh
.fi
.RE
.SH SEE ALSO
.PP
\fB\fCmoray(1)\fR, \fB\fCputbucket(1)\fR, \fB\fCputobject(1)\fR
