.TH listbuckets 1 "January 2017" Moray "Moray Client Tools"
.SH NAME
.PP
listbuckets \- print detailed information about all buckets
.SH SYNOPSIS
.PP
\fB\fClistbuckets [COMMON_OPTIONS]\fR
.SH DESCRIPTION
.PP
Fetches a JSON representation for the configuration of all buckets on the remote
server.  See \fB\fCgetbucket(1)\fR for details about this representation.
.SH OPTIONS
.PP
See \fB\fCmoray(1)\fR for information about the \fB\fCCOMMON_OPTIONS\fR, which control
the log verbosity and how to locate the remote server.
.SH ENVIRONMENT
.PP
See \fB\fCmoray(1)\fR for information about the \fB\fCLOG_LEVEL\fR, \fB\fCMORAY_SERVICE\fR, and
\fB\fCMORAY_URL\fR environment variables.
.SH EXAMPLES
.PP
List details about the buckets on a Moray server:
.PP
.RS
.nf
$ listbuckets
[
  {
    "name": "accounts",
    "index": {
      "loginName": {
        "type": "string",
        "unique": true
      }
    },
    "pre": [],
    "post": [],
    "options": {
      "version": 1
    },
    "mtime": "2017\-01\-27T17:22:32.288Z"
  },
  {
    "name": "accounts_withnames",
    "index": {
      "loginName": {
        "type": "string",
        "unique": true
      },
      "fullName": {
        "type": "string",
        "unique": false
      }
    },
    "pre": [],
    "post": [],
    "options": {
      "version": 2
    },
    "mtime": "2017\-01\-27T17:22:45.965Z"
  }
]
.fi
.RE
.PP
Using the \fB\fCjson(1)\fR tool, you can easily list just the buckets' names:
.PP
.RS
.nf
$ listbuckets | json \-ga name
accounts
accounts_withnames
.fi
.RE
.SH SEE ALSO
.PP
\fB\fCmoray(1)\fR, \fB\fCgetbucket(1)\fR, \fB\fCputbucket(1)\fR,
jsontool \[la]https://github.com/trentm/json\[ra]
